"""create user token table

Revision ID: 4f0e45220a3a
Revises: 2a39ce763a57
Create Date: 2024-01-23 14:00:29.712129

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f0e45220a3a"
down_revision: Union[str, None] = "2a39ce763a57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_token",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("access_token", sa.String(length=450), nullable=False),
        sa.Column("refresh_token", sa.String(length=450), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("access_token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_token")
    # ### end Alembic commands ###
